package com.poly.websitesellphone.Service;



import com.poly.websitesellphone.model.ProductModel;

import java.util.List;

public interface ProductInterface {
    String TABLE_NAME_PRODUCT = "product";
    String TABLE_NAME_IMAGE = "[image]";
    String TABLE_NAME_CATEGORY = "category";
    String COLUMN_ID_PRODUCT = "id_product";
    String COLUMN_ID_CATEGORY = "id_category";
    String COLUMN_NAME = "name_product";
    String COLUMN_SHORT_DESC = "short_desc";
    String COLUMN_DETAIL = "detail";
    String COLUMN_QUANTITY = "quantity";
    String COLUMN_PRICE = "price";
    String COLUMN_DATE_CREATED = "date_created";
    String COLUMN_STATUS = "status_product";
    String COLUMN_ID_IMAGE = "id_image";
    String COLUMN_NAME_IMAGE = "name_image";
    String COLUMN_NAME_CATEGORY = "name_category";
    String GETDATE = "GETDATE()";

    //    String PRODUCT_SELECT_ALL = String.format("SELECT * FROM %s", TABLE_NAME);
    String PRODUCT_SELECT_BY_ID = String.format("SELECT * FROM %s WHERE %s = ?", TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT);
    String PRODUCT_INSERT = String.format("INSERT INTO %s (%s, %s, %s, %s, %s, %s, %s, %s) VALUES (?, ?, ?, ?, ?, ?, %s, ?)", TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, COLUMN_NAME, COLUMN_SHORT_DESC, COLUMN_DETAIL, COLUMN_QUANTITY, COLUMN_PRICE, COLUMN_DATE_CREATED, COLUMN_STATUS, GETDATE);
    String PRODUCT_UPDATE = String.format("UPDATE %s SET %s = ?, %s = ?, %s = ?, %s = ?, %s = ?, %s = ? WHERE %s = ?", TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, COLUMN_NAME, COLUMN_SHORT_DESC, COLUMN_DETAIL, COLUMN_PRICE, COLUMN_STATUS, COLUMN_ID_PRODUCT);
    String PRODUCT_UPDATE_QUANTITY = String.format("UPDATE %s SET %s = %s + ? WHERE %s = ?", TABLE_NAME_PRODUCT, COLUMN_QUANTITY, COLUMN_QUANTITY, COLUMN_NAME);
    String PRODUCT_DELETE = String.format("DELETE FROM %s WHERE %s = ?", TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT);
    String PRODUCT_SELECT_BY_NAME = String.format("SELECT * FROM %s WHERE %s LIKE ?", TABLE_NAME_PRODUCT, COLUMN_NAME);
    String PRODUCT_SELECT_BY_ID_2 = "SELECT p.id_product, p.name_product, p.id_category, p.short_desc, p.detail, p.quantity, p.price, p.date_created, p.status_product, img.name_image FROM product p LEFT JOIN (SELECT i.id_product, i.name_image, ROW_NUMBER() OVER (PARTITION BY i.id_product ORDER BY i.id_image DESC) AS rn FROM image i) img ON p.id_product = img.id_product WHERE p.id_product = ? AND img.rn = 1;";

    // check query before excute()
    String PRODUCT_SELECT_ALL_TEMP = String.format("SELECT %s.%s , %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s FROM %s INNER JOIN %s  ON %s.%s = %s.%s INNER JOIN (SELECT %s, %s, MIN(%s) AS name_image FROM %s GROUP BY %s, %s) %s  ON %s.%s = %s.%s",
            TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_NAME, TABLE_NAME_PRODUCT, COLUMN_SHORT_DESC, TABLE_NAME_PRODUCT, COLUMN_DETAIL, TABLE_NAME_PRODUCT, COLUMN_QUANTITY, TABLE_NAME_PRODUCT, COLUMN_PRICE, TABLE_NAME_PRODUCT, COLUMN_DATE_CREATED, TABLE_NAME_PRODUCT, COLUMN_STATUS, TABLE_NAME_CATEGORY, COLUMN_NAME_CATEGORY, TABLE_NAME_IMAGE, COLUMN_NAME_IMAGE,
            TABLE_NAME_PRODUCT,
            TABLE_NAME_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_CATEGORY, COLUMN_ID_CATEGORY,
            COLUMN_ID_PRODUCT, COLUMN_ID_IMAGE, COLUMN_NAME_IMAGE,
            TABLE_NAME_IMAGE,
            COLUMN_ID_PRODUCT, COLUMN_ID_IMAGE, TABLE_NAME_IMAGE, TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_IMAGE, COLUMN_ID_PRODUCT
    );

    String PRODUCT_SELECT_ALL = String.format("SELECT %s.%s , %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, img.%s FROM %s INNER JOIN %s  ON %s.%s = %s.%s INNER JOIN (SELECT %s, %s, ROW_NUMBER() OVER (PARTITION BY %s ORDER BY %s) AS row_num FROM %s) AS img ON %s.%s = img.%s AND img.row_num = 1;",
            TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_NAME, TABLE_NAME_PRODUCT, COLUMN_SHORT_DESC, TABLE_NAME_PRODUCT, COLUMN_DETAIL, TABLE_NAME_PRODUCT, COLUMN_QUANTITY, TABLE_NAME_PRODUCT, COLUMN_PRICE, TABLE_NAME_PRODUCT, COLUMN_DATE_CREATED, TABLE_NAME_PRODUCT, COLUMN_STATUS, TABLE_NAME_CATEGORY, COLUMN_NAME_CATEGORY, COLUMN_NAME_IMAGE,
            TABLE_NAME_PRODUCT,
            TABLE_NAME_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_CATEGORY, COLUMN_ID_CATEGORY,
            COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, TABLE_NAME_IMAGE, TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, COLUMN_ID_PRODUCT

    );

    String PRODUCT_SELECT_ALL_BY_ID_CART = String.format("SELECT %s.%s , %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, img.%s FROM %s INNER JOIN %s  ON %s.%s = %s.%s INNER JOIN (SELECT %s, %s, ROW_NUMBER() OVER (PARTITION BY %s ORDER BY %s) AS row_num FROM %s) AS img ON %s.%s = img.%s AND img.row_num = 1 INNER JOIN cart_detail cd ON cd.%s = %s.%s WHERE cd.id_cart = ?;",
            TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_NAME, TABLE_NAME_PRODUCT, COLUMN_SHORT_DESC, TABLE_NAME_PRODUCT, COLUMN_DETAIL, TABLE_NAME_PRODUCT, COLUMN_QUANTITY, TABLE_NAME_PRODUCT, COLUMN_PRICE, TABLE_NAME_PRODUCT, COLUMN_DATE_CREATED, TABLE_NAME_PRODUCT, COLUMN_STATUS, TABLE_NAME_CATEGORY, COLUMN_NAME_CATEGORY, COLUMN_NAME_IMAGE,
            TABLE_NAME_PRODUCT,
            TABLE_NAME_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_CATEGORY, COLUMN_ID_CATEGORY,
            COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, TABLE_NAME_IMAGE, TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, COLUMN_ID_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT
    );

    String PRODUCT_SELECT_ALL_BY_ID_CART_DETAIL = String.format("SELECT %s.%s , %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, img.%s FROM %s INNER JOIN %s  ON %s.%s = %s.%s INNER JOIN (SELECT %s, %s, ROW_NUMBER() OVER (PARTITION BY %s ORDER BY %s) AS row_num FROM %s) AS img ON %s.%s = img.%s AND img.row_num = 1 INNER JOIN cart_detail cd ON cd.%s = %s.%s WHERE cd.id_cart_detail = ?;",
            TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_NAME, TABLE_NAME_PRODUCT, COLUMN_SHORT_DESC, TABLE_NAME_PRODUCT, COLUMN_DETAIL, TABLE_NAME_PRODUCT, COLUMN_QUANTITY, TABLE_NAME_PRODUCT, COLUMN_PRICE, TABLE_NAME_PRODUCT, COLUMN_DATE_CREATED, TABLE_NAME_PRODUCT, COLUMN_STATUS, TABLE_NAME_CATEGORY, COLUMN_NAME_CATEGORY, COLUMN_NAME_IMAGE,
            TABLE_NAME_PRODUCT,
            TABLE_NAME_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_CATEGORY, COLUMN_ID_CATEGORY,
            COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, TABLE_NAME_IMAGE, TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, COLUMN_ID_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT
    );

    String PRODUCT_SELECT_ALL_BY_STATUS = String.format("SELECT %s.%s , %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, img.%s FROM %s INNER JOIN %s  ON %s.%s = %s.%s INNER JOIN (SELECT %s, %s, ROW_NUMBER() OVER (PARTITION BY %s ORDER BY %s) AS row_num FROM %s) AS img ON %s.%s = img.%s AND img.row_num = 1 WHERE %s.%s = 1 ORDER BY %s DESC;;",
            TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_NAME, TABLE_NAME_PRODUCT, COLUMN_SHORT_DESC, TABLE_NAME_PRODUCT, COLUMN_DETAIL, TABLE_NAME_PRODUCT, COLUMN_QUANTITY, TABLE_NAME_PRODUCT, COLUMN_PRICE, TABLE_NAME_PRODUCT, COLUMN_DATE_CREATED, TABLE_NAME_PRODUCT, COLUMN_STATUS, TABLE_NAME_CATEGORY, COLUMN_NAME_CATEGORY, COLUMN_NAME_IMAGE,
            TABLE_NAME_PRODUCT,
            TABLE_NAME_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_CATEGORY, COLUMN_ID_CATEGORY,
            COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, TABLE_NAME_IMAGE, TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_STATUS, COLUMN_DATE_CREATED

    );

    String PRODUCT_SELECT_ALL_BY_STATUS_SEARCH = String.format("SELECT %s.%s , %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, img.%s FROM %s INNER JOIN %s  ON %s.%s = %s.%s INNER JOIN (SELECT %s, %s, ROW_NUMBER() OVER (PARTITION BY %s ORDER BY %s) AS row_num FROM %s) AS img ON %s.%s = img.%s AND img.row_num = 1 WHERE %s.%s = 1 AND name_product LIKE ? ORDER BY %s DESC;",
            TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_NAME, TABLE_NAME_PRODUCT, COLUMN_SHORT_DESC, TABLE_NAME_PRODUCT, COLUMN_DETAIL, TABLE_NAME_PRODUCT, COLUMN_QUANTITY, TABLE_NAME_PRODUCT, COLUMN_PRICE, TABLE_NAME_PRODUCT, COLUMN_DATE_CREATED, TABLE_NAME_PRODUCT, COLUMN_STATUS, TABLE_NAME_CATEGORY, COLUMN_NAME_CATEGORY, COLUMN_NAME_IMAGE,
            TABLE_NAME_PRODUCT,
            TABLE_NAME_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_CATEGORY, COLUMN_ID_CATEGORY,
            COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, TABLE_NAME_IMAGE, TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_STATUS, COLUMN_DATE_CREATED

    );

    String PRODUCT_SELECT_ALL_BY_ID_CATEGORY = String.format("SELECT %s.%s , %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, %s.%s, img.%s FROM %s INNER JOIN %s  ON %s.%s = %s.%s INNER JOIN (SELECT %s, %s, ROW_NUMBER() OVER (PARTITION BY %s ORDER BY %s) AS row_num FROM %s) AS img ON %s.%s = img.%s AND img.row_num = 1 WHERE %s.%s = 1 AND product.id_category = ? ORDER BY %s DESC;",
            TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_NAME, TABLE_NAME_PRODUCT, COLUMN_SHORT_DESC, TABLE_NAME_PRODUCT, COLUMN_DETAIL, TABLE_NAME_PRODUCT, COLUMN_QUANTITY, TABLE_NAME_PRODUCT, COLUMN_PRICE, TABLE_NAME_PRODUCT, COLUMN_DATE_CREATED, TABLE_NAME_PRODUCT, COLUMN_STATUS, TABLE_NAME_CATEGORY, COLUMN_NAME_CATEGORY, COLUMN_NAME_IMAGE,
            TABLE_NAME_PRODUCT,
            TABLE_NAME_CATEGORY, TABLE_NAME_PRODUCT, COLUMN_ID_CATEGORY, TABLE_NAME_CATEGORY, COLUMN_ID_CATEGORY,
            COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, COLUMN_ID_PRODUCT, COLUMN_NAME_IMAGE, TABLE_NAME_IMAGE, TABLE_NAME_PRODUCT, COLUMN_ID_PRODUCT, COLUMN_ID_PRODUCT, TABLE_NAME_PRODUCT, COLUMN_STATUS, COLUMN_DATE_CREATED

    );

    public List<ProductModel> selectAll();

    public ProductModel selectAllByIdCartDetail(int idCartDetail);

    public List<ProductModel> selectAllByIdCart(int idCart);

    public ProductModel selectById(int id);

    public int insert(ProductModel productModel);

    public boolean update(ProductModel productModel);

    public boolean updateQuantity(int quantity, String nameProduct);

    public boolean delete(int id);

    public List<ProductModel> selectByName(String name);

}
